AWSTemplateFormatVersion: 2010-09-09
Description: Simple example with SQS
Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 6

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties: { }
    
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref Queue
      PolicyDocument:
        Id: !Sub ${AWS::StackName}-queue-policy
        Version: 2012-10-17
        Statement:
          - Sid: Allow receive message
            Effect: Allow
            Principal:
              AWS: '*'
            Action: SQS:ReceiveMessage
            Resource: !GetAtt Queue.Arn
#            You should limit that policy by setting example Condition:
#            Condition:
#              ArnEquals:
#                aws:SourceArn: <RESOURCE-ARN>
          - Sid: Allow send message
            Effect: Allow
            Principal: '*'
            Action: SQS:SendMessage
            Resource: !GetAtt Queue.Arn
#            You should limit that policy by setting example Condition:
#            Condition:
#              ArnEquals:
#                aws:SourceArn:
#                  - <RESOURCE-ARN>
#                  - <RESOURCE-ARN>