Transform: AWS::Serverless-2016-10-31
Description: Example of Lambda Function in .NET Core
Resources:
  HelloDotnetLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AwsLambdaDotnet.Functions::AwsLambdaDotnet.Functions.FunctionClass::Invoke
      Runtime: dotnetcore3.1
      CodeUri: bin/Release/netcoreapp3.1/publish
      MemorySize: 1024
      Timeout: 10