AWSTemplateFormatVersion: 2010-09-09
Description: Example of inline policies
Resources:

  # An inline policy which allows to perform decrypt operation using all kms keys. This is inline policy defined as a separate resource. It can be associated with multiple roles.
  # This technique is useful if you want to define a policy that is used in multiple roles.
  SomeInlinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SomeInlinePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: kms:Decrypt
            Resource: '*'
      Roles:
        - !Ref FirstRole
        - !Ref SecondRole

  FirstRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        # An inline policy can be defined inside a role.
        - PolicyName: InvokeFunctions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: '*'
      # Assume role policy document tells which service can assume this role. Actually means which service can be associated with this role.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  SecondRole:
    Type: AWS::IAM::Role
    Properties:
      # Assume role policy document tells which service can assume this role. Actually means which service can be associated with this role.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com