AWSTemplateFormatVersion: 2010-09-09
Description: Example of using managed policies
Resources:

  # Managed policies can be referenced in multiple roles, also outside the stack where they were created. 
  # For example, we can define managed policy in some stack to allow using particular resources in that stack 
  # and export that managed policy to use in some other role in other stack.
  SomeManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow using KMS keys in default encryption in S3 buckets
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
            Effect: Allow

  # Managed policy can be used in role by referring that in ManagedPolicyArns property
  RoleUsingManagedPolicy:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - !Ref SomeManagedPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com